### ISSUE TITLE
Need to handle the creation of new directories

### ISSUE THREAD

**Issue by SteveIves** [hippiehunter/VMSBuildSync#1]
If a new folder is created inside of a synced folder on Windows, then a new file is added in that folder, it is not currently syncd, and an error message is displayed:

synchronizing D:\VMSBuildSyncTest\SOURCE\SUBS failed with because it didnt exist on disk (deleted before fsw got to it?)

I assume that the FSW can detect new folders, so we need to respond appropriately.

**Comment by hippiehunter** [comment]
If you check, I think you will find that the file you created had no contents. Currently we don't attempt to sync empty files. FSW detects new folders and files just fine.

**Comment by SteveIves** [comment]
You're right about the empty file thing, but there is still an issue. If I create a folder and drop in a file with content, an SftpPathNotFoundException exception is thrown and the file is not transferred. Here I created a new folder FRED and then dropped in a file PPROG.DBL:
```
NO-LOGGER: 1/13/2021 22:00:08: syncing files from D:\VMSBuildSyncTest\SOURCE\FRED -> /DKA0/USER/STEVEI/VMSBUILDSYNCTEST/FRED failed with Renci.SshNet.Common.SftpPathNotFoundException: syserr: no such file or directory, or no privilege for attempted operation, file: /DKA0/USER/STEVEI/VMSBUILDSYNCTEST/FRED
   at Renci.SshNet.Common.AsyncResult.EndInvoke() in D:\VMSBuildSync\SSH.NET\src\Renci.SshNet\Common\AsyncResult.cs:line 100
   at Renci.SshNet.Common.AsyncResult`1.EndInvoke() in D:\VMSBuildSync\SSH.NET\src\Renci.SshNet\Common\AsyncResult.cs:line 204
   at Renci.SshNet.SftpClient.EndListDirectory(IAsyncResult asyncResult) in D:\VMSBuildSync\SSH.NET\src\Renci.SshNet\SftpClient.cs:line 537
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at VMSBuildSync.RemoteSync.<>c__DisplayClass31_0.<<ListDirectoryAsync>b__1>d.MoveNext() in D:\VMSBuildSync\VMSBuildSync\RemoteSync.cs:line 535
--- End of stack trace from previous location where exception was thrown ---
   at VMSBuildSync.RemoteSync.SSHRetryReset[T](SftpClient sftp, Func`1 action) in D:\VMSBuildSync\VMSBuildSync\RemoteSync.cs:line 465
   at VMSBuildSync.RemoteSync.ListDirectoryAsync(SftpClient sftp, String path) in D:\VMSBuildSync\VMSBuildSync\RemoteSync.cs:line 533
   at VMSBuildSync.RemoteSync.SyncDirectoryAsync(String sourcePath, String destinationPath, String searchPattern) in D:\VMSBuildSync\VMSBuildSync\RemoteSync.cs:line 193
NO-LOGGER: 1/13/2021 22:00:08: synchronizing failed for D:\VMSBuildSyncTest\SOURCE\FRED\PROG.DBL, sync was requested but the remote system had a newer version or something went wrong
NO-LOGGER: 1/13/2021 22:00:14: synchronizing D:\VMSBuildSyncTest\SOURCE\FRED failed with because it didnt exist on disk (deleted before fsw got to it?)
```
